async function main() {
}

main().catch((reason) => {
    console.log('Error:', reason)
})
